### ISSUE TITLE
File upload download issue

### ISSUE THREAD

**Issue by dyzdyz010** [flagrow/upload#126]
- flagrow/upload extension version: <0.6.0>
- flarum version: 0.1.0-beta.7
- Upload adapter causing issues: local

---

Uploaded a zip file successfully then download it, an `error json file` was downloaded, with content below:

```
{"errors":[{"code":500,"title":"Internal server error","detail":"Flagrow\\Upload\\Exceptions\\InvalidDownloadException: cURL error 3: \u003Curl\u003E malformed (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) in \/Users\/dyz\/Sites\/flarum\/vendor\/flagrow\/upload\/src\/Downloader\/DefaultDownloader.php:46\nStack trace:\n#0 \/Users\/dyz\/Sites\/flarum\/vendor\/flagrow\/upload\/src\/Commands\/DownloadHandler.php(86): Flagrow\\Upload\\Downloader\\DefaultDownloader-\u003Edownload(Object(Flagrow\\Upload\\File), Object(Flagrow\\Upload\\Commands\\Download))\n#1 [internal function]: Flagrow\\Upload\\Commands\\DownloadHandler-\u003Ehandle(Object(Flagrow\\Upload\\Commands\\Download))\n#2 \/Users\/dyz\/Sites\/flarum\/vendor\/illuminate\/bus\/Dispatcher.php(202): call_user_func(Array, Object(Flagrow\\Upload\\Commands\\Download))\n#3 [internal function]: Illuminate\\Bus\\Dispatcher-\u003EIlluminate\\Bus\\{closure}(Object(Flagrow\\Upload\\Commands\\Download))\n#4 \/Users\/dyz\/Sites\/flarum\/vendor\/illuminate\/pipeline\/Pipeline.php(139): call_user_func(Object(Closure), Object(Flagrow\\Upload\\Commands\\Download))\n#5 [internal function]: Illuminate\\Pipeline\\Pipeline-\u003EIlluminate\\Pipeline\\{closure}(Object(Flagrow\\Upload\\Commands\\Download))\n#6 \/Users\/dyz\/Sites\/flarum\/vendor\/illuminate\/pipeline\/Pipeline.php(102): call_user_func(Object(Closure), Object(Flagrow\\Upload\\Commands\\Download))\n#7 \/Users\/dyz\/Sites\/flarum\/vendor\/illuminate\/bus\/Dispatcher.php(204): Illuminate\\Pipeline\\Pipeline-\u003Ethen(Object(Closure))\n#8 \/Users\/dyz\/Sites\/flarum\/vendor\/illuminate\/bus\/Dispatcher.php(177): Illuminate\\Bus\\Dispatcher-\u003EdispatchNow(Object(Flagrow\\Upload\\Commands\\Download), NULL)\n#9 \/Users\/dyz\/Sites\/flarum\/vendor\/flagrow\/upload\/src\/Api\/Controllers\/DownloadController.php(60): Illuminate\\Bus\\Dispatcher-\u003Edispatch(Object(Flagrow\\Upload\\Commands\\Download))\n#10 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/Handler\/ControllerRouteHandler.php(53): Flagrow\\Upload\\Api\\Controllers\\DownloadController-\u003Ehandle(Object(Zend\\Stratigility\\Http\\Request))\n#11 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/DispatchRoute.php(69): Flarum\\Http\\Handler\\ControllerRouteHandler-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Array)\n#12 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(212): Flarum\\Http\\Middleware\\DispatchRoute-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#13 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(88): Zend\\Stratigility\\Dispatch-\u003EdispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\DispatchRoute), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#14 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(160): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#15 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/SetLocale.php(51): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#16 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(212): Flarum\\Http\\Middleware\\SetLocale-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#17 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(88): Zend\\Stratigility\\Dispatch-\u003EdispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\SetLocale), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#18 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(160): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#19 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/AuthenticateWithHeader.php(58): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#20 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(212): Flarum\\Http\\Middleware\\AuthenticateWithHeader-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#21 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(88): Zend\\Stratigility\\Dispatch-\u003EdispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\AuthenticateWithHeader), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#22 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(160): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#23 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/AuthenticateWithSession.php(36): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#24 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(212): Flarum\\Http\\Middleware\\AuthenticateWithSession-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#25 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(88): Zend\\Stratigility\\Dispatch-\u003EdispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\AuthenticateWithSession), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#26 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(160): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#27 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/RememberFromCookie.php(39): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#28 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(212): Flarum\\Http\\Middleware\\RememberFromCookie-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#29 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(88): Zend\\Stratigility\\Dispatch-\u003EdispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\RememberFromCookie), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#30 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(160): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#31 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/StartSession.php(48): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#32 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(212): Flarum\\Http\\Middleware\\StartSession-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#33 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(88): Zend\\Stratigility\\Dispatch-\u003EdispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\StartSession), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#34 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(160): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#35 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Api\/Middleware\/FakeHttpMethods.php(33): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#36 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(212): Flarum\\Api\\Middleware\\FakeHttpMethods-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#37 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(88): Zend\\Stratigility\\Dispatch-\u003EdispatchCallableMiddleware(Object(Flarum\\Api\\Middleware\\FakeHttpMethods), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#38 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(160): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#39 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/ParseJsonBody.php(31): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#40 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(212): Flarum\\Http\\Middleware\\ParseJsonBody-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#41 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(88): Zend\\Stratigility\\Dispatch-\u003EdispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\ParseJsonBody), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#42 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(160): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#43 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Api\/Middleware\/HandleErrors.php(45): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#44 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(212): Flarum\\Api\\Middleware\\HandleErrors-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#45 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(88): Zend\\Stratigility\\Dispatch-\u003EdispatchCallableMiddleware(Object(Flarum\\Api\\Middleware\\HandleErrors), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#46 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(160): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#47 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/MiddlewarePipe.php(111): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#48 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/AbstractServer.php(55): Zend\\Stratigility\\MiddlewarePipe-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\NoopFinalHandler))\n#49 \/Users\/dyz\/Sites\/flarum\/vendor\/zendframework\/zend-diactoros\/src\/Server.php(157): Flarum\\Http\\AbstractServer-\u003E__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), Object(Zend\\Stratigility\\NoopFinalHandler))\n#50 \/Users\/dyz\/Sites\/flarum\/vendor\/flarum\/core\/src\/Http\/AbstractServer.php(36): Zend\\Diactoros\\Server-\u003Elisten(Object(Zend\\Stratigility\\NoopFinalHandler))\n#51 \/Users\/dyz\/Sites\/flarum\/api.php(16): Flarum\\Http\\AbstractServer-\u003Elisten()\n#52 {main}"}]}
```

**Comment by luceos** [comment]
What's the mime configuration you use?

**Comment by dyzdyz010** [comment]
^application\/.*(x-(7z|rar)-compressed|zip|arj|x-(bzip2|gzip|lha|stuffit|tar)|pdf)

local

Default file download template

**Comment by luceos** [comment]
Would you be able to inspect the headers of the file download? I think it somehow attempts to set up the mime configuration incorrectly..

**Comment by dyzdyz010** [comment]
Response headers are as follows:

```
HTTP/1.1 500 Internal Server Error
Date: Tue, 09 Jan 2018 01:36:37 GMT
Server: Apache/2.4.28 (Unix) PHP/7.1.7
X-Powered-By: PHP/7.1.7
Connection: close
Transfer-Encoding: chunked
Content-Type: application/vnd.api+json
```

One other detail is that I'm running this site on a subdomain, like `localhost/flarum/`

System version: macOS 10.13.2

**Comment by emillod** [comment]
I have the same error... Can anyone help me?

**Comment by luceos** [comment]
In order to debug this properly I need to see the database entry for the requested file in `flagrow_files`.

**Comment by dyzdyz010** [comment]
I reproduced this issue today and here's what's in `flagrow_files` of the uploaded zip file:

```
|  7 |        1 |          NULL |    NULL | acgpower2313.zip | 2018-06-20/1529455890-468874-acgpower2313.zip | /flarum/assets/files/2018-06-20/1529455890-468874-acgpower2313.zip | application/zip | 2558736 | local         | 0000-00-00 00:00:00 | NULL      | 9f51a538-b489-43f7-b091-b378b300487e | file          |
```

**Comment by luceos** [comment]
Forgot to ask for any useful entries inside `storage/logs/flarum.log` related to the 500 internal server error.

Sorry to bother.

**Comment by dyzdyz010** [comment]
Sorry but I'm afraid there's nothing relative to this, checked the file no recent log written.

**Comment by luceos** [comment]
And anything in the site or webserver error logs? A 500 internal server error is always logged somewhere.

**Comment by dyzdyz010** [comment]
Sorry after some debugging I found that I filled in a wrong `Content Delivery URL` and causes a URL-malform error of cURL. I left it blank and now it works!🤪
