### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by thistehneisen** [flagrow/upload#129]
- flagrow/upload extension version: 0.6.0
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: local

---

```Request URL:http://x.y/api/flagrow/upload
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:5.79.Z.F:80
Referrer Policy:no-referrer-when-downgrade
Connection:keep-alive
Content-Type:application/vnd.api+json
Date:Wed, 21 Feb 2018 11:20:24 GMT
Server:nginx
Transfer-Encoding:chunked
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.9,lv;q=0.8,ru;q=0.7,und;q=0.6,da;q=0.5
Connection:keep-alive
Content-Length:3796110
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryHplCWnjLhakJjHXB
Cookie:flarum_session=iivi9rs1tv063kaiuiri39cpa6; flarum_remember=4dAWUmab72EQC6laJ8wcfVyDhHuZ8nv4rKRHnfhN
Host:x.y
Origin:http://x.y
Referer:http://x.y/d/4-xy
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
X-CSRF-Token:qPsgtOCqAd8WDZVm1aXHvAGgmNBhCusLSLspOSTC
------WebKitFormBoundaryHplCWnjLhakJjHXB
Content-Disposition: form-data; name="files[]"; filename="i can't feel my face w x&g.mp3"
Content-Type: audio/mp3

------WebKitFormBoundaryHplCWnjLhakJjHXB--

forum-11c1c3d7.js:594 POST http://x.y/api/flagrow/upload 500 (Internal Server Error)
createXhr @ forum-11c1c3d7.js:594
ajax @ forum-11c1c3d7.js:596
m.request @ forum-11c1c3d7.js:623
request @ forum-11c1c3d7.js:2038
uploadFiles @ forum-11c1c3d7.js:2420
process @ forum-11c1c3d7.js:2419
(anonymous) @ forum-11c1c3d7.js:309```

**Comment by luceos** [comment]
What does `storage/logs/flarum.log` say?

**Comment by thistehneisen** [comment]
```production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
Stack trace:
#0 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\DispatchRoute->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#1 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\DispatchRoute), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#2 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#3 /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#4 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\SetLocale->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#5 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\SetLocale), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#6 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#7 /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(36): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#8 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\AuthenticateWithSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#9 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\AuthenticateWithSession), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#10 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#11 /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(39): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#12 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\RememberFromCookie->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#13 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\RememberFromCookie), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#14 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#15 /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/StartSession.php(48): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#16 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\StartSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#17 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\StartSession), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#18 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#19 /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(31): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#20 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\ParseJsonBody->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#21 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\ParseJsonBody), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#22 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#23 /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(61): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#24 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\HandleErrors->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#25 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\HandleErrors), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#26 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#27 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(111): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#28 /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/AbstractServer.php(55): Zend\Stratigility\MiddlewarePipe->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\NoopFinalHandler))
#29 /var/www/vhosts/x.y/httpdocs/vendor/zendframework/zend-diactoros/src/Server.php(157): Flarum\Http\AbstractServer->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Zend\Stratigility\NoopFinalHandler))
#30 /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\Diactoros\Server->listen(Object(Zend\Stratigility\NoopFinalHandler))
#31 /var/www/vhosts/x.y/httpdocs/index.php(16): Flarum\Http\AbstractServer->listen()
#32 {main}  ```

**Comment by luceos** [comment]
That's a NotFoundException (it's missing the first and most important line)? Those can be ignored.

**Comment by thistehneisen** [comment]
She was playing hide and seek:
`[2018-02-21 12:16:14] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62`

**Comment by luceos** [comment]
@thistehneisen 😂 

Even so, those exceptions can be ignored.

**Comment by thistehneisen** [comment]
Nothing else quite interesting in the log:
```root@herpderp:/var/www/vhosts/x.y/httpdocs/storage/logs# cat flarum.log | grep DEBUG
[2018-02-21 08:22:04] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:22:54] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:34:34] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:34:40] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:38:52] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:38:52] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:40:23] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:41:08] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:41:32] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:48:09] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 08:58:01] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 09:18:36] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 10:11:26] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 10:28:08] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 10:33:05] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 10:34:19] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 10:35:20] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 10:35:37] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 10:46:46] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 10:55:26] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:03:43] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:03:43] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:04:01] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:04:18] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:05:00] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:05:41] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:06:20] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:07:04] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:41:31] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:42:06] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:51:48] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 11:57:13] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
[2018-02-21 12:16:14] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /var/www/vhosts/x.y/httpdocs/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62

**Comment by luceos** [comment]
Have you enabled debug and check the debug button in the error popup?

**Comment by thistehneisen** [comment]
Well, just did. Now I can go sit in a corner, cause it's upload_max_filesize @ php.ini.
