### ISSUE TITLE
Error after file select

### ISSUE THREAD

**Issue by piotrkochan** [flagrow/upload#59]
```
Uncaught TypeError: Cannot read property 'data' of null
    at UploadButton.success (http://ubu:81/assets/forum-b5304c3d.js:35058:53)
    at http://ubu:81/assets/forum-b5304c3d.js:2539:22
    at thennable (http://ubu:81/assets/forum-b5304c3d.js:2510:5)
    at fire (http://ubu:81/assets/forum-b5304c3d.js:2530:4)
    at Deferred.self.resolve (http://ubu:81/assets/forum-b5304c3d.js:2447:5)
    at http://ubu:81/assets/forum-b5304c3d.js:2482:15
    at Array.map (native)
    at finish (http://ubu:81/assets/forum-b5304c3d.js:2480:9)
    at http://ubu:81/assets/forum-b5304c3d.js:2557:7
    at thennable (http://ubu:81/assets/forum-b5304c3d.js:2510:5)
```

**Comment by Luceos** [comment]
@piotrkochan what upload adapter do you use and what version of this extension and flarum?

**Comment by Luceos** [comment]
Closing, no response.
